# Generated by Django 3.1.2 on 2020-10-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='stores.storebook')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_store_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
