# Generated by Django 3.1.2 on 2020-10-29 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_storebooksubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storebooksubscription',
            unique_together={('store_book', 'subscriber')},
        ),
    ]
